RESEARCH=/home/Documents/Senior_Design
PLAYERC=$(RESEARCH)/player-3.0.2
R_INC=-I$(PLAYERC)/ -I$(PLAYERC)/client_libs/ -I$(PLAYERC)/build/

regular:
	gcc $(R_INC) -o basic basic.c -lplayerc

clean:
	rm -f basic
