CC=diet gcc
CFLAGS=-nostdinc
RESEARCH=/home/chryel/Documents/Senior_Design/code
LIBCDIR=$(RESEARCH)/dietlibc-0.33/bin-i386
PLAYER=$(RESEARCH)/player-3.0.2
SRCDIR=$(RESEARCH)/static_libplayerc
INC=-I$(SRCDIR)/ -I$(SRCDIR)/player_build/ -I$(SRCDIR)/player_build/libplayerinterface/ -I$(SRCDIR)/player_include/
